blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/cristian-cardona-dev/professional-evolution-portfolio/issues
    about: Ask a question or start a discussion in the issue tracker.
